### ISSUE TITLE
Upload still limited even with size_t change.

### ISSUE THREAD

**Issue by Atomzwieback** [openswoole/swoole-src#127]
Please answer these questions before submitting your issue.

What did you do? If possible, provide a simple script for reproducing the error.
I tried to upload a file larger than 4GB via swoole and it seems like it causes some kind of error. Seems like you changed the int to size_t which should allow uploads as large as the memory of the host machine is but that is not the case. May there are parts in the code that can not handle a big size_t

What did you expect to see?
I expect swoole to allow uploads as big as the memory is.

What did you see instead?
We have a size limit about 4GB, i expect this not to be the case and be able to upload files as big as my memory is.

What version of Swoole are you using (show your php --ri swoole)?
openswoole-4.9.1

What is your machine environment used (show your uname -a & php -v & gcc -v) ?
Linux 5.4.0-81-generic Ubuntu SMP x86_64 GNU/Linux

PHP 8.1.1 (cli) (built: Dec 21 2021 20:02:26) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies

gcc version 8.3.0

**Comment by doubaokun** [comment]
It is not recommended to upload large files with OpenSwoole at this stage.

Duplicate with https://github.com/openswoole/swoole-src/issues/24

You can try changing `package_max_length` = 4 * 1024 * 1024 * 1024 according to https://openswoole.com/docs/modules/swoole-server/configuration
