### ISSUE TITLE
Build fails on Apple Silicon: ld: library not found for -latomic

### ISSUE THREAD

**Issue by ryandesign** [openswoole/swoole-src#131]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

Compile openswoole 4.10.0 with php 7.2.x or 7.3.x on a Mac with an Apple Silicon (arm64) processor

2. What did you expect to see?

successful compile

3. What did you see instead?

```
ld: library not found for -latomic
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?

4.10.0

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

macOS 11 on Apple Silicon (arm64)

php 7.2.34 or php 7.3.33

Problem does not occur with php 7.4.27 or later

Apple clang version 12.0.5 (clang-1205.0.22.11)

This was caused by 63d95ec9ea3d9e1de5d78cc705b8da04cfd42f7f. Reverting that fixes it.

**Comment by doubaokun** [comment]
Because PHP 7.2 & 7.3 are not supported by PHP team, we have removed the tests from OpenSwoole CI.

Reviewing if we still want to support 7.2/7.3, otherwise we will remove 7.2/7.3 versions from package.xml in the next release.

**Comment by doubaokun** [comment]
Closed by https://github.com/openswoole/swoole-src/pull/138
