### ISSUE TITLE
Server stats change depending on the worker where it is executed

### ISSUE THREAD

**Issue by acelaya** [openswoole/swoole-src#133]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

I created an endpoint that returns the result of `$server->stats()`. I was trying to use it to do some profiling of an app, focusing on the "top_classes" block.

However, it seems to return a different result depending on the worker handling the request.

It kind of makes sense at some extent, as the memory is not shared between workers, once the server is started. However, its usefulness is limited this way.

Maybe I'm doing something wrong, or not understanding how the stats are supposed to be used.

2. What did you expect to see?

A consistent response, specifically on the "top_classes" block, regardless of the worker handling the request.

3. What did you see instead?

A rotating response, that apparently depends on the worker handling the request.

4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?

4.9.1

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Alpine.

**Comment by doubaokun** [comment]
It is supposed to be working like this due to the structure of server. In a busy running production server the response should be similar when requests are load balanced to each server.

**Comment by acelaya** [comment]
I guess that makes sense.

Thanks for the clarification.
