### ISSUE TITLE
http_index_files not working in http2 mode

### ISSUE THREAD

**Issue by hauptmedia** [openswoole/swoole-src#134]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

Using HTTP/1.x the index.html will be served, with http2 the request is not working

`<?php
Swoole\Coroutine::set([
    'trace_flags' => SWOOLE_TRACE_HTTP2,
    'log_level' => 0,
]);
$key_dir = __DIR__ . '/../ssl/';
$http = new swoole_http_server("0.0.0.0", 9501, SWOOLE_BASE, SWOOLE_SOCK_TCP | SWOOLE_SSL);
$http->set([
    'open_http2_protocol' => 1,
    'enable_static_handler' => TRUE,
    'document_root' => __DIR__,
    'enable_coroutine' => true,
    'http_index_files' => ['index.html', 'index.txt'],
    'ssl_cert_file' => $key_dir . '/example.com+4.pem',
    'ssl_key_file' => $key_dir . '/example.com+4-key.pem',
]);

$http->on('request', function (swoole_http_request $request, swoole_http_response $response) {
	$response->header('Access-Control-Allow-Origin', '*');
    $response->header('Content-Type', 'text/event-stream');
    $response->header('Cache-Control', 'no-cache');
    $response->header('X-Accel-Buffering', 'no');

    while(1) {
        $response->write("event: ping\n\n");
        $r = $response->write("data: {\"time\": \"" . date(DATE_ISO8601) . "\"}\n\n");
        if(!$r) return;
        co::sleep(1);
    }
    
    $response->end(__DIR__);
});

$http->start();
`

2. What did you expect to see?

index.html should be served using http2

3. What did you see instead?

Canceled Request

4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?

4.10.0

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

PHP 8.1.2 (cli) (built: Jan 21 2022 04:34:05) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by doubaokun** [comment]
Fixed and supported at https://github.com/openswoole/swoole-src/pull/137

**Comment by 0utc0ntr0l2021** [comment]
> Fixed and supported at [#137](https://github.com/openswoole/ext-openswoole/pull/137)

not working now
