### ISSUE TITLE
[Question] How to install on Windows 8.1?

### ISSUE THREAD

**Issue by tsahi-gisha** [openswoole/swoole-src#142]
Is there a guide or tutorial on how to install openswoole on Windows 8.1?

**Comment by doubaokun** [comment]
WSL is required when installing on Windows. Complete openswoole installation guide: https://openswoole.com/docs/get-started/installation

**Comment by tsahi-gisha** [comment]
But where is no WSL on Windows 8.1.
Is it possible to install using cygwin perhaps?

**Comment by doubaokun** [comment]
It is recommended to use Docker or virtual machine if WSL is not supported.
