### ISSUE TITLE
When running in HTTP2 mode: if a worker dies the connection becomes stale

### ISSUE THREAD

**Issue by hauptmedia** [openswoole/swoole-src#151]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

Running HTTP Server in PROCESS mode with HTTP2 enabled. If a worker dies (e.g. due to unhandled exception) the HTTP2 connection becomes stale and it's not possible to do a reload in Google Chrome.

```
<?php
Swoole\Coroutine::set([
    'trace_flags' => SWOOLE_TRACE_HTTP2,
    'log_level' => 0,
]);
$key_dir = __DIR__ . '/../ssl/';
$http = new swoole_http_server("0.0.0.0", 9501, SWOOLE_PROCESS, SWOOLE_SOCK_TCP | SWOOLE_SSL);
$http->set([
    'open_http2_protocol' => 1,
    'enable_static_handler' => TRUE,
    'document_root' => __DIR__,
    'enable_coroutine' => true,
    'ssl_cert_file' => $key_dir . '/example.com+4.pem',
    'ssl_key_file' => $key_dir . '/example.com+4-key.pem',
]);


$http->on('request', function (swoole_http_request $request, swoole_http_response $response) {

        $response->header('Access-Control-Allow-Origin', '*');
    $response->header('Content-Type', 'text/event-stream');
    $response->header('Cache-Control', 'no-cache');
    $response->header('X-Accel-Buffering', 'no');

    while(1) {
        $response->write("event: ping\n\n");
        $r = $response->write("data: {\"time\": \"" . date(DATE_ISO8601) . "\"}\n\n");
        if(!$r) return;
        co::sleep(1);
        throw new \Exception();
    }

    $response->end(__DIR__);
});

$http->start();

```

2. What did you expect to see?

The HTTP2 connection should be aborted if the worker dies.

3. What did you see instead?

I guess it tries to multiplex with the still open but invalid HTTP2 connection. Running the same code with HTTP1 closes the connection correctly.

4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?

openswoole

Open Swoole => enabled
Author => Open Swoole Group <hello@openswoole.com>
Version => 4.10.0
Built => Jan 25 2022 13:16:13
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 3.0.1 14 Dec 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
mysqlnd => enabled
async_redis => enabled
postgresql => enabled

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

PHP 8.1.2 (cli) (built: Jan 21 2022 04:34:05) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by doubaokun** [comment]
HTTP2 connection should be closed when the worker handling the connection is crashed.
