### ISSUE TITLE
Improve flaky tests

### ISSUE THREAD

**Issue by hauptmedia** [openswoole/swoole-src#159]
Hi,

i want to discuss the situation about flaky test runs. The current tests sometimes fail and we have to run them many times with fingers crossed to get all "green".

I think it's really important that we improve the situation on the tests. Are there already any thoughts or started efforts to improve this?

Cheers,

Julian

**Comment by doubaokun** [comment]
There are many poorly created tests to be fixed although some are fixed. You are welcome to send PR to fix the tests.

We have a openswoole kernel dev slack group for regular contributors, welcome to join: 

https://docs.google.com/forms/d/e/1FAIpQLScqpkPJeFG-ss3P-KhFECDSNLyo1iKmU1DToIQX9YRWbuetjw/viewform

Best,
Bruce
