### ISSUE TITLE
Gracefully Shutdown

### ISSUE THREAD

**Issue by appaydin** [openswoole/swoole-src#177]
While the HTTP server is shutting down, can we cancel the shutdown if there are pending tasks in the queue?

I want to implement graceful shutdown.

1. Shutdown Server -> "Send SIGTERM signal to Manager Process"
2. Wait for active connections to complete, reject new connections.
3. If there is work in the queue (Swoole Task), wait.
4. Shutdown.

Is there such a feature in the shutdown command?

**Comment by mhkarimi1383** [comment]
Hi @cesurapp 
did you implemented this procedure successfully?

**Comment by cesurapp** [comment]
> Hi @cesurapp did you implemented this procedure successfully?

https://openswoole.com/docs/modules/swoole-server/configuration#max_wait_time

When the shutdown signal is sent, it waits for a maximum of "max_wait_time". It is waiting for the transactions that were active during this period to be completed. Keeping the duration high ensures that the transactions are completed.
