### ISSUE TITLE
problem install in cpanel

### ISSUE THREAD

**Issue by AngusDV** [openswoole/swoole-src#189]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
 sudo /opt/cpanel/ea-php80/root/usr/bin/pecl install swoole

2. What did you expect to see?
install success

3. What did you see instead?
411 source files, building
running: phpize
enable sockets supports? [no] : yes
enable openssl support? [no] : 
enable http2 support? [no] : 
enable mysqlnd support? [no] : 
enable json support? [no] : 
enable curl support? [no] : 
building in /root/tmp/pear/pear-build-rootdVQTr8/swoole-4.8.8
running: /root/tmp/pear/swoole/configure --with-php-config=/opt/cpanel/ea-php80/root/usr/bin/php-config --enable-sockets=yes --enable-openssl=no --enable-http2=no --enable-mysqlnd=no --enable-swoole-json=no --enable-swoole-curl=no
sh: /root/tmp/pear/swoole/configure: No such file or directory
ERROR: `/root/tmp/pear/swoole/configure --with-php-config=/opt/cpanel/ea-php80/root/usr/bin/php-config --enable-sockets=yes --enable-openssl=no --enable-http2=no --enable-mysqlnd=no --enable-swoole-json=no --enable-swoole-curl=no' failed

4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?
4.8.8

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
 `gcc -v`
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 

`php -v` 
PHP 8.0.16 (cli) (built: Mar 17 2022 00:43:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.16, Copyright (c) Zend Technologies

`uname -a`
Linux vps1708.tmdvps.com 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by doubaokun** [comment]
Please follow the installation guidelines at https://openswoole.com/docs/get-started/installation
