### ISSUE TITLE
Version compatible with PHP 7.2

### ISSUE THREAD

**Issue by michaelchandrag** [openswoole/swoole-src#200]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
I tried to install every stable version from openswoole from 4.10.0 - 4.8.1 for php 7.2
```
In file included from /usr/include/php/20170718/main/php.h:40:0,
                 from /tmp/pear/temp/openswoole/php_swoole.h:20,
                 from /tmp/pear/temp/openswoole/ext-src/php_swoole_private.h:25,
                 from /tmp/pear/temp/openswoole/ext-src/php_swoole_cxx.h:19,
                 from /tmp/pear/temp/openswoole/ext-src/php_swoole_server.h:21,
                 from /tmp/pear/temp/openswoole/ext-src/php_swoole_http_server.h:21,
                 from /tmp/pear/temp/openswoole/ext-src/swoole_http_response.cc:17:
/usr/include/php/20170718/Zend/zend_API.h: In function ‘void php_swoole_http_response_cookie(zend_execute_data*, zval*, bool)’:
/usr/include/php/20170718/Zend/zend_API.h:774:97: warning: ‘_i’ may be used uninitialized in this function [-Wmaybe-uninitialized]
      zend_wrong_parameter_type_error(_flags & ZEND_PARSE_PARAMS_THROW, _i, _expected_type, _arg); \
                                                                                                 ^
/usr/include/php/20170718/Zend/zend_API.h:734:7: note: ‘_i’ was declared here
   int _i; \
       ^
/usr/include/php/20170718/Zend/zend_API.h:763:2: note: in expansion of macro ‘ZEND_PARSE_PARAMETERS_START_EX’
  ZEND_PARSE_PARAMETERS_START_EX(0, min_num_args, max_num_args)
  ^
/tmp/pear/temp/openswoole/ext-src/swoole_http_response.cc:918:5: note: in expansion of macro ‘ZEND_PARSE_PARAMETERS_START’
     ZEND_PARSE_PARAMETERS_START(1, 9)
     ^


```

2. What did you expect to see?
success install using php7.2

3. What did you see instead?
error installation

4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?
tried to install using 4.10.0, 4.9.1, 4.8.1

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Linux myhost 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

PHP 7.2.17-1+ubuntu16.04.1+deb.sury.org+3 (cli) (built: Apr 10 2019 10:50:19) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.17-1+ubuntu16.04.1+deb.sury.org+3, Copyright (c) 1999-2018, by Zend Technologies
    with blackfire v1.55.0~linux-x64-non_zts72, https://blackfire.io, by Blackfire

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.12' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)

**Comment by doubaokun** [comment]
PHP7.2 is end of life according to PHP team, please upgrade to >= PHP7.4
