### ISSUE TITLE
Uknown event type stop on Process\Pool

### ISSUE THREAD

**Issue by SpiritSaint** [openswoole/swoole-src#201]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.

> 1. I copy the full [coroutine TCP server](https://openswoole.com/docs/modules/swoole-coroutine-tcp-server-full-process-server-example).
> 2. I add a event callback for stop on pool. 
> 3. I ran the code.

2. What did you expect to see?

No error message.

3. What did you see instead?

```
 ErrorException 

  Swoole\Process\Pool::on(): unknown event type[stop]

  at app/Console/Commands/Server/Run.php:42
     38▕         echo swoole_version();
     39▕ 
     40▕         $pool->on('stop', function() {
     41▕             echo "Process Pool is stopping.\n";
  ➜  42▕         });
     43▕ 
     44▕         // By enabling this, each callback to WorkerStart will automatically create a coroutine for you
     45▕         $pool->set(['enable_coroutine' => true]);
     46▕ 

  1   app/Console/Commands/Server/Run.php:42
      Swoole\Process\Pool::on()

      +13 vendor frames 
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?

4.11.0

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

Fedora 34
PHP 8.1

**Comment by doubaokun** [comment]
Should be on `WorkerStop`
