### ISSUE TITLE
Swoole/Table weird behaviour/bug

### ISSUE THREAD

**Issue by JustHarris** [openswoole/swoole-src#204]
Please answer these questions before submitting your issue.

1. What did you do? If possible, provide a simple script for reproducing the error.
- We have a Swoole\Table with 8192 rows, each row consists in one field (String 8172)
```
$this->hitsTable = new Table(8192);
$this->hitsTable->column('event', Table::TYPE_STRING, 8172);
$this->hitsTable->create();
``` 

We write to this table from 8 workers, each worker adds about 50 rows per second, generating a random key (md5(some fields + random integers ) that, from our side, it seems impossible that it generates collisions. (although, if there is a collision, it should be ok, as the only consequence should be that the value is replaced)
```
md5(microtime(true) . $item[0] . $item[2] . random_int(0, 999999));
```

This Table is read every 2 seconds from another worker, iterating through the table and storing the keys to be deleted.  

```
$this->lookupTable->rewind();
for ($i = 0; $i < $maxItemsToSend; $i++) {
    $item = $this->lookupTable->current();
    $tableKey = $this->lookupTable->key();
    if (!empty($item["event"]) && $this->lookupTable->exists($tableKey)) {
        $eventsRepo[] = unserialize($item["event"]);
    }
    if (!empty($tableKey)) {
        $eventsToDelete[] = $tableKey;
    }
    $this->lookupTable->next();
}
```

After reading all table values, we delete those that have been extracted.
```
foreach ($eventsToDelete as $key) {
    if ($this->lookupTable->exists($key)) {
        $this->lookupTable->del($key);
    } else {
        $this->logger->error("Timer #{$this->id} Queue #{$this->queue} -> Key {$key} do not exists", "Manager");
    }
}
```

There are no other process that can delete elements from the table, but while deleting, there are other processes adding new rows. 

2. What did you expect to see?
The elements are stored, read and deleted.

3. What did you see instead?
At some point after running the server for some minutes/hours, one element could be found iterating through the Table, stored in the $keysToDelete array, but, when you try to delete it (we check with `exists($key)`), it doesn't exist. This element then remains in the table forever.
If we try to delete it directly, the process sometimes get stuck forever. 

After this happens, the table rejects to sets some keys (about 0.5-1%) with this message 
```
failed to set key value, try to increase the table_size
```
But the table never has more than 1000 entries (the declared size in the creation is 8192)
This behavior continues until the pod is restarted. One (or more) elements are in the table when we iterate over it, but when you call exists() it doesn't exist, and many set() fail.  
 

4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?
We use your docker image openswoole/swoole:4.11-php8.1 

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
root@b6c151687af9:/usr/local/src/app# uname -a              
Linux b6c151687af9 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 GNU/Linux

root@b6c151687af9:/usr/local/src/app# php -v       
PHP 8.1.0 (cli) (built: Dec  2 2021 12:11:39) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.0, Copyright (c), by Zend Technologies

root@b6c151687af9:/usr/local/src/app# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6) 
```

**Comment by doubaokun** [comment]
@JustHarris Can you try to test with 81920 slots? The slots number are not the capacity of table. Or provide a simple script to reproduce the issue?

**Comment by alamagus** [comment]
@JustHarris 

> This Table is read every 2 seconds from another worker, iterating through the table and storing the keys to be deleted.

If, by any chance, you're using [Timer::tick()](https://openswoole.com/docs/modules/swoole-timer-tick) for reading/deleting rows every 2s, it might explain the problem. Say, if reading/deleting operation takes 3s, you might end up running two tick callbacks, 1 of which deletes rows, and the second traverses through the table.

https://wiki.swoole.com/#/memory/table
Here it says that you shouldn't delete table rows while traversing through it

**Comment by doubaokun** [comment]
Feel free to reopen it if you can provide a script to reproduce the issue.
