### ISSUE TITLE
Randomly throwing WARNING ProcessPool::wait(): worker#7 abnormal exit, status=0, signal=13

### ISSUE THREAD

**Issue by acelaya** [openswoole/swoole-src#220]
1. What did you do? If possible, provide a simple script for reproducing the error.

I have started to notice some requests failing in my server. I have an nginx in front of my openswoole-based app, that was returning 502 statuses randomly.

I checked the logs of my application, and it was printing some random lines like this one, always matching the time of the failing requests:

`WARNING	ProcessPool::wait(): worker#7 abnormal exit, status=0, signal=13`

The worker number changes, but the rest is always the same.

I'm not aware of having done anything different recently, but I guess understanding what this warning means would probably help me find what is wrong. I have searched and haven't found any documentation relative to this.

My application is running with 16 web workers and 16 task workers, and some requests might trigger tasks.

2. What did you expect to see?

No errors in the logs and all requests working properly.

3. What did you see instead?

The warning described above, followed by a failed request.

4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?
```
# php --ri openswoole

openswoole

Open Swoole => enabled
Author => Open Swoole Group <hello@openswoole.com>
Version => 4.11.0
Built => Apr 23 2022 09:58:09
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
spinlock => enabled
rwlock => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```
5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
# uname -a
Linux ff7c15bffeda 5.15.0-27-generic #28-Ubuntu SMP Thu Apr 14 04:55:28 UTC 2022 x86_64 Linux

# php -v
PHP 8.1.5 (cli) (built: Apr 18 2022 23:48:54) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.5, Copyright (c) Zend Technologies

# gcc -v
/bin/sh: gcc: not found
```

There's no `gcc`, as this is running on Alpine.

**Comment by doubaokun** [comment]
@acelaya please upgrade to the latest version 4.11.1, if you still see the issues we will investigate further.

**Comment by acelaya** [comment]
Thanks! I will try and monitor it for a while

**Comment by acelaya** [comment]
I have just deployed it this morning with openswoole 4.11.1

I'll monitor it for a couple of days and close this if I'm not able to reproduce it anymore.

**Comment by acelaya** [comment]
I can confirm this happens with openswoole 4.11.1 as well.

**Comment by doubaokun** [comment]
@acelaya Could you provide a simple script to reproduce the issue?

**Comment by acelaya** [comment]
I still need to manage to understand the circumstances in which this happens, but I'll do my best to come up with something.

What I have seen is that this happens almost always with one specific endpoint. I guess there's something different there.

**Comment by acelaya** [comment]
I have the suspicion this could be related with CPU usage.

I'm monitoring the server resources, and this consistently happens when the CPU hits 100% during the request. When that happens, it seems the worker processing the request gets killed. That's why I almost always see this happening with one specific endpoint which is more resource greedy.

**Comment by doubaokun** [comment]
When CPU is used up there could be any exceptions. Feel free to open this when you have more clues.
