### ISSUE TITLE
Features request: Add origin and replace server response header in WebSocket

### ISSUE THREAD

**Issue by AmitSonkhiya** [openswoole/swoole-src#231]
I would like to have the following two features available in OpenSwoole for WebSocket.

### 1: Add allowed origin

Currently, even a localhost or anonymous server may try to establish a WebSocket connection. There should be an option to limit origins so that only authorized apps or websites could attempt to create a WebSocket connection.

For example, an application could be served via a website (say example.com) or a corresponding (Android/iOS) app. In that case, it should have an option to allow WS connection to only that website and the app.

Although there is the `on Open` event and the `request` object contains the `origin` field to validate the origin further, it still requires manual processing. 
Additionally, this feature is related to handling CORS, hence should be a part of the framework itself like [Socket.IO](https://socket.io/docs/v3/handling-cors/).

### 2: Replace server response header

After a successful WebSocket connection, the response header returned by the server contains the `Server: OpenSwoole 4.11.1` entry.

```
Connection: Upgrade
Sec-WebSocket-Accept: mABCD0joUS/Z/yPYqrqfa3+I2sT=
Sec-WebSocket-Version: 13
Server: OpenSwoole 4.11.1
Upgrade: websocket
```

Could it have a feature to completely remove this server header line or replace it with a fake name like `Server: XYZ`?

Both features would strongly enhance security from an end programmer's perspective.

Thanks

**Comment by doubaokun** [comment]
You can validate the Origin header by overriding the on handshake callback: https://openswoole.com/docs/modules/swoole-websocket-server-on-handshake.

New server option `enable_server_token` will be available in the next version.
