### ISSUE TITLE
Swoole websocket server freezing or connection timeouts

### ISSUE THREAD

**Issue by ben74** [openswoole/swoole-src#242]
Hi, I'm trying to implement a websocket server based on swoole for various clients, for handling queue and pubsub a the same time, within a low memory environment in order to keep it as tiny as possible ..

Given a swoole websocket server ( with 1 reactor and 1 worker ) who correctly handle messages, around 250 connections with a 10 message scenario, or 5 seconds, with all previous connections closed ( scenario : pushes a message to a queue, then consume another one, spread through 3 different queues ) then all further connections goes timeout

With openswoole4.1.1, the worker totally freeze, don't have any more connection opened logs
With swoole5, the worker dont freeze, the tick and logs are there, still connection timeout forever

I've tried with gracefully restarting server->stop(-1) && server->start() but it doesn't solve anything

With Those docker Images : [alptech/yuzu:shiva](https://hub.docker.com/layers/177224418/alptech/yuzu/shiva/images/sha256-f77eb609d42918453e83fed5234ca6c9064b0c7effc8ad09cedd74d402270ac0?context=repo) or [alptech/yuzu:shiva8](https://hub.docker.com/layers/277902774/alptech/yuzu/shiva8/images/sha256-08aee09e649ad300829d8d559dbca7c2f1b8e5d225ed93c601c73c1990e8ff7e?context=repo) -> has the entrypoint performing the whole stuff in https://github.com/ben74/Shiva/blob/master/demo/stressTest.sh
which launches
https://github.com/ben74/Shiva/blob/master/demo/websocket-server.php
then 300 clients via
https://github.com/ben74/Shiva/blob/master/demo/stressTest.php

and the logs display all timeout errors ( passed a number of connections )
there is huge amount of unused code and comments in websocket-server, due to experimentations

Both scripts can be executed straight ahead on any environment with php and swoole ex : in your terminal, just touching common.php whose functions arent used in this scenario :)

Any help, clue, notice, comment, enlightenment, acknowledgment would be greatly appreciated 😄 
Regards 👍

**Comment by doubaokun** [comment]
Can you provide minimum script to reproduce the issue?

**Comment by ben74** [comment]
When booting both docker images [alptech/yuzu:shiva](https://hub.docker.com/layers/177224418/alptech/yuzu/shiva/images/sha256-f77eb609d42918453e83fed5234ca6c9064b0c7effc8ad09cedd74d402270ac0?context=repo) or [alptech/yuzu:shiva8](https://hub.docker.com/layers/277902774/alptech/yuzu/shiva8/images/sha256-08aee09e649ad300829d8d559dbca7c2f1b8e5d225ed93c601c73c1990e8ff7e?context=repo) performs :
https://github.com/ben74/Shiva/blob/master/demo/stressTest.sh
which launches 
https://github.com/ben74/Shiva/blob/master/demo/websocket-server.php
then 300 clients via
https://github.com/ben74/Shiva/blob/master/demo/stressTest.php

and the logs display all timeout errors ( passed a number of connections )

**Comment by doubaokun** [comment]
Please provide minimum script to reproduce the issue without other codes and dependencies. Fell free to open a new issue following the issue template.
