### ISSUE TITLE
Different Number of Worker Processes Created

### ISSUE THREAD

**Issue by fakharksa** [openswoole/swoole-src#249]
1. What did you do? If possible, provide a simple script for reproducing the error.
```
**Context:**
I am using Smf\ConnectionPool library version v1.0.16 for postgreSQL Connection Pool, installed using 
`composer require open-smf/connection-pool: ~1.0`

Server Configuration sets worker_num as 4 and task_worker_num as 8

My server listens to port 9501.

I test the number of "processes" created when provide same Connection Pool code in $server->on("request", callback() { ... my code ...} and in $server->on("WorkerStart", callback() { ... my same code .. }

**The Code:**

```
            $pool1 = new ConnectionPool(
                [
                    'minActive'         => 10,
                    'maxActive'         => 30,
                    'maxWaitTime'       => 5,
                    'maxIdleTime'       => 20,
                    'idleCheckInterval' => 10,
                ],
                new CoroutinePostgreSQLConnector,
                [
                    'connection_strings' => 'host=127.0.0.1;port=5432;dbname=muasheratdb;user=postgres;password=passwd123',
                ]
            );
            $pool1->init();
            $this->addConnectionPool('pgsql', $pool1);

And, i use the command below on ubuntu terminal to list the processes created:
`sudo lsof -i:9501`

```
2. What did you expect to see?
```
The list should show 14 processes whether the code is used in onRequest or in onWorkerStart. (including Master Process, Manager Process, Worker Processes (4), and Task Worker Processes(8))

```
3. What did you see instead?
```
When Code is supplied in onRequest event, i get number of processes correctly as 14 processes.

BUT when i supply the code in onWorkerStart, i get lesser number of Processes equal to 11.

**Note:** The expected output of SQL Query shown in Postman is showing correct, in both cases.
```
4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?
```
Openswoole version 4.11.1

Note: I installed it by compiling source coce.
```
5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
**Output of uname -a (where fakhar is my name in my computer-name "fakhar-HP-laptop".**
Linux fakhar-HP-Laptop 5.17.5-76051705-generic #202204271406165150484020.04~63e51bd-Ubuntu SMP PREEMPT Wed Ma x86_64 x86_64 x86_64 GNU/Linux

**"Output of php -v"**
PHP 8.1.10 (cli) (built: Sep 18 2022 10:26:02) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies
with Zend OPcache v8.1.10, Copyright (c), by Zend Technologies

**"Output of gcc -v"**

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.2.0-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-gBFGDP/gcc-11-11.2.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (Ubuntu 11.2.0-19ubuntu1)

```

You can also try the following OpenSwoole support channels:

* [Documentation](https://openswoole.com/docs) - Documentation for Open Swoole
* [Slack](https://goo.gl/forms/wooTTDmhbu30x4qC3) - Slack channel of Open Swoole
* [Discord](https://discord.gg/5QC57RNPpw) - Discord server of Open Swoole

**Comment by doubaokun** [comment]
Could you provide code to reproduce the issue?

**Comment by fakharksa** [comment]
> Could you provide code to reproduce the issue?

Please, close the issue as i fixed a bug in my code which solved this issue. Thank you.
