### ISSUE TITLE
Way to integrate GD or Imagick extensions with docker compose

### ISSUE THREAD

**Issue by WraShadow** [openswoole/swoole-src#252]
1. What did you do? If possible, provide a simple script for reproducing the error.
```
I setup openswoole using docker-compose and I was trying to implement a image manipulation library but they seem to require either GD or Imagick, but I cannot seem to find a way to activate the extension.

```
2. What did you expect to see?
```
No error

```
3. What did you see instead?
```
ImageMagick module not available with this PHP installation.
The same happens with GD.

```
4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?
```
openswoole/swoole:4.11-php8.1

```
You can also try the following OpenSwoole support channels:

* [Documentation](https://openswoole.com/docs) - Documentation for Open Swoole
* [Slack](https://goo.gl/forms/wooTTDmhbu30x4qC3) - Slack channel of Open Swoole
* [Discord](https://discord.gg/5QC57RNPpw) - Discord server of Open Swoole

**Comment by WraShadow** [comment]
Is there anything else I can provide to help?

**Comment by schalkt** [comment]
Create a custom Dockerfile and use that in docker-compose.yml.

```Dockerfile
FROM phpswoole/swoole:5.0-php8.1

# Enable extensions
RUN apt-get update && apt-get install -y --no-install-recommends libpng-dev \
	&& docker-php-ext-install gd
```

```Yaml
swoole5:
        restart: unless-stopped
        build:
            context: [path-to-dockerfile]
            dockerfile: ./Dockerfile
```

**Comment by WraShadow** [comment]
Thank you. It worked.
