### ISSUE TITLE
Will there be config.w32?

### ISSUE THREAD

**Issue by rhaikal** [openswoole/swoole-src#272]
1. What did you do? If possible, provide a simple script for reproducing the error.
```
I want to install openswoole extension using php-sdk.
but when I want to configure, it show "Must be run from the root of the extension source"
then I search it and found that it need config.w32, otherwise it won't work
so my question is. Will there be config.w32?

```
2. What did you expect to see?
```
create openswoole.dll

```
3. What did you see instead?
```
"Must be run from the root of the extension source" in php-sdk

```
4. What version of OpenSwoole are you using (show your `php --ri openswoole`)?
```
4.12.0

```
5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
```
Window
PHP 8.1.12 (ts)
gcc version 6.3.0

```

**Comment by doubaokun** [comment]
Unfortunately, openswoole doesn’t work on windows OS. You can find more about how to install at https://openswoole.com/docs/get-started/installation

**Comment by rhaikal** [comment]
awh ok , thanks
