### ISSUE TITLE
openswoole vs swoole - what's going on?

### ISSUE THREAD

**Issue by Draghmar** [openswoole/swoole-src#28]
Hi
I have noticed that you've split for some reason. What's going on? I see that both projects are active...Are they gonna be compatible with each other? Swoole's website redirects to openswoole's when clicking on English language.
I'd like to know which version should I use because now I'm quite confused...

**Comment by rela589n** [comment]
Hello, @doubaokun , 

How did the story continue? It seems that this security issue has been eliminated from ext-swoole, or am I mistaken?

**Comment by rela589n** [comment]
It seems that repository doesn't have code-string with https:// other than tests

https://github.com/search?q=repo%3Aswoole%2Fswoole-src+%28%22%5C%27https%3A%2F%2F%22+OR++%22%5C%22https%3A%2F%2F%22+%29+AND+%28NOT+path%3A*.phpt%29&type=code

**Comment by sorshion** [comment]
@rela589n [see](https://github.com/swoole/swoole-src/issues/4434)

**Comment by rela589n** [comment]
Thank you @sorshion

**Comment by waghanza** [comment]
This story seems a bit confusing a new comer. As I can see the security is now solved, maybe the time then to merge swoole and openswoole

**Comment by rela589n** [comment]
I would also suggest this idea, but it's the question of authors and their relationships, not just a security concern.
