### ISSUE TITLE
[22.0.0] Class OpenSwoole\Coroutine\Server not found

### ISSUE THREAD

**Issue by bcalik** [openswoole/swoole-src#290]
I'm trying to create a Coroutine TCP Server as documented in https://openswoole.com/docs/modules/swoole-coroutine-server

The quick start example in documentation doesn't work on 22.0.0

> Uncaught Error: Class "OpenSwoole\Coroutine\Server" not found

**Comment by bcalik** [comment]
> It is deprecated in v22, please use https://openswoole.com/docs/modules/swoole-http-server-doc

How can I start it as Coroutine? I want to subscribe and listen Redis and start an TCP server at the same time.

I tried using Coroutine hooks but it didn’t work.

**Comment by doubaokun** [comment]
Use https://openswoole.com/docs/modules/swoole-server-doc
