### ISSUE TITLE
[5.0] Native PSR7 spec support 

### ISSUE THREAD

**Issue by doubaokun** [openswoole/swoole-src#38]
To better support upper layer frameworks and application, http messages should follow PSR7 spec.

**Comment by aiira-co** [comment]
Wouldn't it be better to create a PSR7 Bridge lib to just convert swoole http message to standard psr7

**Comment by aiira-co** [comment]
![swoole](https://user-images.githubusercontent.com/28719431/139528380-bc32cf9a-6226-45f6-83e4-fccd21fd5221.jpg)
> Wouldn't it be better to create a PSR7 Bridge lib to just convert swoole http message to standard psr7

I do that with my framework at https://github.com/aiira-co/spatial-core/tree/main/src/swoole and uses it like so at index

**Comment by doubaokun** [comment]
Thanks, by providing the native support will save the overhead of the downstream frameworks.

**Comment by doubaokun** [comment]
Supported from v22 which will be available soon.
