### ISSUE TITLE
[4.9.0] Expose server metrics to prometheus and external monitoring infra

### ISSUE THREAD

**Issue by doubaokun** [openswoole/swoole-src#41]
Provide PHP layer function to expose server metrics to external monitoring system

**Comment by pachico** [comment]
What are the current exposed metrics OpenSwoole provides?

**Comment by doubaokun** [comment]
@pachico You can get the server metrics with `Swoole\Server->stats()`, check more at https://www.swoole.co.uk/docs/modules/swoole-server-stats

**Comment by pachico** [comment]
In that case, a simple formatter should be enough. 
I can volunteer to write it.

**Comment by doubaokun** [comment]
@pachico you are welcome to involve the development by submitting PR. I can send you more details about this, please find me at the Slack channel. Thanks.

**Comment by pachico** [comment]
Cool @doubaokun , thanks.
However, I was actually thinking about a PHP library that reads from `Swoole\Server->stats()` and exposes metrics in Prometheus format, not something that makes parts of Swoole itself.

**Comment by doubaokun** [comment]
It is fine to create your own package to do the task, although there will be a built-in feature to expose these metrics.

**Comment by doubaokun** [comment]
Release note: https://www.swoole.co.uk/article/openswoole-4.9.0-released
