### ISSUE TITLE
pecl install fails if there is multiple php versions

### ISSUE THREAD

**Issue by tolgaulas** [openswoole/swoole-src#50]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Our system is multi php (7.3 and 8.0) with the default is php7.3, but pecl install it into 8.0 lib folder:
Installing '/usr/include/php/20200930/ext/openswoole/config.h'
Installing '/usr/include/php/20200930/ext/openswoole/php_swoole.h'
Installing '/usr/lib/php/20200930/openswoole.so'

2. What did you expect to see?
pecl install to the default php version (7.3)

3. What did you see instead?
swoole is installed to the 8.0 library folder

4. What version of Open Swoole are you using (show your `php --ri openswoole`)?
4.7.2

**Comment by doubaokun** [comment]
You have to link php correctly like this if there are multiple version PHP on your machine:

```
ln -sf /opt/php/php8/bin/php /usr/bin/php
ln -sf /opt/php/php8/bin/phpize /usr/bin/phpize
ln -sf /opt/php/php8/bin/php-config /usr/bin/php-config
```
