### ISSUE TITLE
Swoole Postgres version mismatch

### ISSUE THREAD

**Issue by ipranjal** [openswoole/swoole-src#56]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

while running make && make install on ext-postgres

2. What did you expect to see?

I except to successfully build extension

3. What did you see instead?

Instead I see the following error "Ext version does not match the Open Swoole version"

4. What version of Open Swoole are you using (show your `php --ri openswoole`)?

Version => 4.7.2

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
macOS Big Sur Intel version 

on further digging I found out it checks for SWOOLE_API_VERSION_ID < 0x202109a but the api version for openswoole 4.7.2 is SWOOLE_API_VERSION_ID 0x202012a
 so ext-postgres will never install successfully

**Comment by doubaokun** [comment]
Please check the master branch again, v4.7.2 is supported now: https://github.com/openswoole/ext-postgresql/pull/4

We will provide native support for PG in the future versions and merge ext-postgresql into ext-openswoole.

**Comment by ipranjal** [comment]
Thanks , I was using the 4.7.2 checkout
