### ISSUE TITLE
Http Request Batching Example

### ISSUE THREAD

**Issue by tlaverdure** [openswoole/swoole-src#64]
Hey there, I'm trying to figure out if Swoole can receive many http requests and process the incoming data in batches? I've read through the docs and [Master Swoole PHP](https://www.amazon.com/Mastering-Swoole-PHP-performance-concurrent-ebook/dp/B0881B227S) (which does mention batching but I couldn't find any examples). 

What I've been able to come up with is the following process:

1. Create a table to capture requests
2. Create a timer that checks for requests on an interval (in this case 1 second)
3. Remove the request from the table and add it to a batch array to do something with
4. Star the server and write request data to the table

```php
$table = new Swoole\Table(1024 * 1024);
$table->column('data', Swoole\Table::TYPE_STRING, 1024);
$table->create();

$server = new Swoole\Http\Server('127.0.0.1', 6001);

$server->on('start', function () use ($table) {
    Swoole\Timer::tick(1000, function () use ($table) {
        if ($table->count() === 0) {
            return;
        }

        $batch = [];

        foreach ($table as $key => $value) {
            $batch[$key] = $value['data'];
            $table->del($key);
        }

        $count = count($batch);

        print("Processing batch of {$count} requests" . PHP_EOL);
    });
});

$server->on('request', function ($request, $response) use ($table) {
    // $id = uniqid();
    $id = md5(uniqid() . ' ' . microtime() . ' ' . rand(0, 10000));
    $table->set("request:$id", ['data' => $request->getContent()]);
    $response->end('ok');
});

$server->start();
```

~~This seems to work OK until I test it in a high throughput situation. Deleting items from the table does not seem to happen quick enough which results in duplicates in the batch process.~~ Looks like I was being naive with `uniqId()` and it was the culprit here.

<details>
    <summary>Sample Output</summary>

```
$ wrk -t 2 -c 100 -d 10 --latency http://localhost:6001
Running 10s test @ http://localhost:6001
  2 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   599.28us  110.80us   3.68ms   74.50%
    Req/Sec    73.61k     1.45k   75.62k    95.54%
  Latency Distribution
     50%  606.00us
     75%  666.00us
     90%  717.00us
     99%  812.00us
  1479364 requests in 10.10s, 214.45MB read
Requests/sec: 146446.67
Transfer/sec:     21.23MB
```

``` bash
$ php server.php
Processing batch of 33252 requests
Processing batch of 139284 requests
Processing batch of 145218 requests
Processing batch of 146185 requests
Processing batch of 137315 requests
Processing batch of 141549 requests
Processing batch of 146930 requests
Processing batch of 139085 requests
Processing batch of 139635 requests
Processing batch of 146278 requests
Processing batch of 108778 requests
Processing batch of 3984 requests
Processing batch of 1330 requests
Processing batch of 444 requests
Processing batch of 148 requests
Processing batch of 48 requests
Processing batch of 16 requests
Processing batch of 6 requests
Processing batch of 2 requests
Processing batch of 0 requests
Processing batch of 0 requests
Processing batch of 0 requests
```

</details>

~~Also note that `$table->count()` never reaches `0` even though all the rows should have been deleted~~ (id was not unique enough 😄 ). 

Is there a better and more efficient way to achieve this?

**Comment by tlaverdure** [comment]
Fixed the issues with `$table->count()`. There were some key conflicts causing undesirable results when deleting rows. So let's just focus on, "is there a better way to do this"?

**Comment by doubaokun** [comment]
The concept is correct, but please make sure the batching operation is meaningful, for example merger multiple MySQL query into one.

**Comment by tlaverdure** [comment]
@doubaokun thanks for taking a look and sharing feedback. Much appreciated.
