### ISSUE TITLE
Installation Error "header file <ares.h> not found", when installing "OpenSwoole" from sourcecode

### ISSUE THREAD

**Issue by fakharak** [openswoole/swoole-src#65]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
Ran Command to install OpenSwoole from source-code, as below:
```
cd /tmp && git clone https://github.com/openswoole/swoole-src.git && \
    cd swoole-src && \
    git checkout v4.7.2 && \
    phpize8.0  && \
    ./configure --enable-openssl \
                --enable-mysqlnd \
                --enable-sockets \
                --enable-http2 \
                --enable-swoole-curl \
                --enable-swoole-json \
                --enable-debug \
                --enable-debug-log \
                --enable-trace-log \
                --enable-thread-context \
                --enable-cares \
                --with-php-config=/usr/bin/php-config8.0 && \
    sudo make && sudo make install
```

And, before running the command above, i also installed c-ares library on ubuntu using command below:
`sudo apt-get install -y libc-ares2`

2. What did you expect to see?
Successful installation.

3. What did you see instead?
 Error Message: /tmp/swoole-src/ext-src/php_swoole.cc:54:10: fatal error: ares.h: No such file or directory

4. What version of Open Swoole are you using (show your `php --ri openswoole`)?
4.7.2

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?
Ubuntu 18.04 (Bionic)
PHP8.0
![swoole_installation_issue](https://user-images.githubusercontent.com/9947110/141655705-01e16b90-8802-44fe-9892-91e5823d8481.png)

**Comment by fakharak** [comment]
The issue resolved by installing "libc-ares-dev", then removed the "swoole-src" folder, and re-installing openswoole from source again (starting from cloning git repo), so pre-requisite to configure compile-time swoole option "--enable-cares" is:
`sudo apt-get install -y libc-ares-dev`

**Comment by doubaokun** [comment]
Instruction added at https://www.swoole.co.uk/docs/get-started/installation#general-parameters
