### ISSUE TITLE
PHP 8.1.0RC6 issue

### ISSUE THREAD

**Issue by 3kbest** [openswoole/swoole-src#71]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.

`Unknown error type: [8192]: Return type of Swoole\ArrayObject::rewind() should either be compatible with Iterator::rewind(): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in @swoole-src/library/core/ArrayObject.php on line 80`

2. What did you expect to see?

n/a

3. What did you see instead?

n/a

4. What version of Open Swoole are you using (show your `php --ri openswoole`)?

Compiled from Master - 20.11.2021

```
openswoole

Open Swoole => enabled
Author => Open Swoole Group & Contributors <hello@swoole.co.uk>
Version => 4.7.2
Built => Nov 20 2021 22:37:49
coroutine => enabled with boost asm context
epoll => enabled
eventfd => enabled
signalfd => enabled
cpu_affinity => enabled
spinlock => enabled
rwlock => enabled
sockets => enabled
openssl => OpenSSL 1.1.1f  31 Mar 2020
dtls => enabled
http2 => enabled
json => enabled
mutex_timedlock => enabled
pthread_barrier => enabled
futex => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => On => On
swoole.unixsock_buffer_size => 8388608 => 8388608
```

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

`Linux  5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

`PHP 8.1.0RC6 (cli) (built: Nov 19 2021 06:49:51) (NTS)`

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
```

**Comment by doubaokun** [comment]
Please try to compile the master branch with 8.1rc6 support. @3kbest

**Comment by doubaokun** [comment]
8.1 will be supported by the next release.

**Comment by 3kbest** [comment]
I compiled from the master branch - 20.11.2021
https://www.swoole.co.uk/docs/get-started/installation#building-swoole-from-source

Maybe I did something wrong. Can try again later today

**Comment by doubaokun** [comment]
You can skip or remove this command `git checkout v4.7.2`, then you are installing master branch.

**Comment by 3kbest** [comment]
I was innstalling it to wrong php version. php-config was still on php8.0
https://askubuntu.com/questions/890366/how-change-the-phpize-to-match-the-php-version

Looks like its works now
