### ISSUE TITLE
Pecl install requires libpq-fe.h (Postgres) even though --with-postgres=n

### ISSUE THREAD

**Issue by benwills** [openswoole/swoole-src#93]
Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a simple script for reproducing the error.
`pecl install openswoole-4.8.1`

Full output at the bottom of this issue.

Also note that this is a brand new installation of ubuntu 18.04, just upgraded to 20.04. This is a bare metal install, and not a virtualized install. I have installed some things necessary for php8.1, and that is it. (my php module list is below)

This may also be important: the first time I tried to install openswoole on this machine, I selected 'y' for postgres support. When it failed, I tried setting it to 'n'. When that also failed, I tried deleting pear's cache and selecting 'n' again. When that failed, I rebooted and selected 'n' again. I rebooted a couple more times, and the install failed every time in the same was as what I've pasted at the bottom of this issue.

2. What did you expect to see?

I expected the installation to run successfully

3. What did you see instead?

That it failed requiring Postgres, even though I selected 'n' for Postgres support.

4. What version of Open Swoole are you using (show your `php --ri openswoole`)?

Attempting to install openswoole-4.8.1 from pecl, on php8.1

5. What is your machine environment used (show your `uname -a` & `php -v` & `gcc -v`) ?

uname -a
  
    Linux s187667 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

php -v
  
    PHP 8.1.0 (cli) (built: Nov 25 2021 20:22:03) (NTS)
    Copyright (c) The PHP Group
    Zend Engine v4.1.0, Copyright (c) Zend Technologies
        with Zend OPcache v8.1.0, Copyright (c), by Zend Technologies

gcc -v
  
    Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)

php -m
  
    [PHP Modules]
    calendar
    Core
    ctype
    curl
    date
    dba
    dom
    exif
    FFI
    fileinfo
    filter
    ftp
    gd
    gettext
    hash
    iconv
    igbinary
    imap
    intl
    json
    libxml
    mbstring
    mysqli
    mysqlnd
    openssl
    pcntl
    pcre
    PDO
    pdo_mysql
    pdo_pgsql
    pdo_sqlite
    pgsql
    Phar
    posix
    readline
    Reflection
    session
    shmop
    SimpleXML
    sockets
    sodium
    SPL
    sqlite3
    standard
    sysvmsg
    sysvsem
    sysvshm
    tidy
    tokenizer
    xml
    xmlreader
    xmlwriter
    xsl
    Zend OPcache
    zip
    zlib
    
    [Zend Modules]
    Zend OPcache
    
full install output:
    
    # pecl install openswoole-4.8.1
    WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
    downloading openswoole-4.8.1.tgz ...
    Starting to download openswoole-4.8.1.tgz (1,623,495 bytes)
    .................................................................................................................................................................................................................................................................................................................................done: 1,623,495 bytes
    447 source files, building
    running: phpize
    Configuring for:
    PHP Api Version:         20210902
    Zend Module Api No:      20210902
    Zend Extension Api No:   420210902
    enable sockets supports? [no] : y
    enable openssl support? [no] : y
    enable http2 support? [no] : y
    enable mysqlnd support? [no] : y
    enable json support? [no] : y
    enable curl support? [no] : y
    enable postgres support? [no] : n
    building in /tmp/pear/temp/pear-build-customeriMr8YV/openswoole-4.8.1
    running: /tmp/pear/temp/openswoole/configure --with-php-config=/usr/bin/php-config --enable-sockets=y --enable-openssl=y --enable-http2=y --enable-mysqlnd=y --enable-swoole-json=y --enable-swoole-curl=y --with-postgres=n
    checking for grep that handles long lines and -e... /bin/grep
    checking for egrep... /bin/grep -E
    checking for a sed that does not truncate output... /bin/sed
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for cc... cc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.out
    checking for suffix of executables...
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether cc accepts -g... yes
    checking for cc option to accept ISO C89... none needed
    checking how to run the C preprocessor... cc -E
    checking for icc... no
    checking for suncc... no
    checking for system library directory... lib
    checking if compiler supports -R... no
    checking if compiler supports -Wl,-rpath,... yes
    checking build system type... x86_64-pc-linux-gnu
    checking host system type... x86_64-pc-linux-gnu
    checking target system type... x86_64-pc-linux-gnu
    checking for PHP prefix... /usr
    checking for PHP includes... -I/usr/include/php/20210902 -I/usr/include/php/20210902/main -I/usr/include/php/20210902/TSRM -I/usr/include/php/20210902/Zend -I/usr/include/php/20210902/ext -I/usr/include/php/20210902/ext/date/lib
    checking for PHP extension directory... /usr/lib/php/20210902
    checking for PHP installed headers prefix... /usr/include/php/20210902
    checking if debug is enabled... no
    checking if zts is enabled... no
    checking for gawk... no
    checking for nawk... nawk
    checking if nawk is broken... no
    checking enable debug log... no
    checking enable trace log... no
    checking enable sockets support... y
    checking enable openssl support... y
    checking enable http2.0 support... y
    checking swoole support... yes, shared
    checking enable mysqlnd support... y
    checking enable postgreSQL support... n
    checking enable c-ares support... no
    checking dir of openssl... no
    checking dir of jemalloc... no
    checking enable asan... no
    checking whether to enable swoole coverage support... no
    checking whether to enable Swoole developer build flags... no
    checking whether to enable Swoole JSON build flags... y
    checking whether to enable Swoole CURL build flags... y
    checking whether to enable thread context... no
    checking if compiling with clang... no
    checking for cc option to accept ISO C99... none needed
    checking for accept4 in -lc... yes
    checking for signalfd in -lc... yes
    checking for eventfd in -lc... yes
    checking for epoll_create in -lc... yes
    checking for poll in -lc... yes
    checking for sendfile in -lc... yes
    checking for kqueue in -lc... no
    checking for backtrace in -lc... yes
    checking for daemon in -lc... yes
    checking for mkostemp in -lc... yes
    checking for inotify_init in -lc... yes
    checking for malloc_trim in -lc... yes
    checking for inotify_init1 in -lc... yes
    checking for ptrace in -lc... yes
    checking for getrandom in -lc... yes
    checking for arc4random in -lc... no
    checking for pthread_rwlock_init in -lpthread... yes
    checking for pthread_spin_lock in -lpthread... yes
    checking for pthread_mutex_timedlock in -lpthread... yes
    checking for pthread_barrier_init in -lpthread... yes
    checking for pthread_mutexattr_setpshared in -lpthread... yes
    checking for pthread_mutexattr_setrobust in -lpthread... yes
    checking for pthread_mutex_consistent in -lpthread... yes
    checking for pcre_compile in -lpcre... no
    checking for ares_gethostbyname in -lcares... yes
    checking for gzgets in -lz... yes
    checking for BrotliEncoderCreateInstance in -lbrotlienc... yes
    checking for BrotliDecoderCreateInstance in -lbrotlidec... yes
    checking for cpu affinity... yes
    checking for socket REUSEPORT... yes
    checking for futex... yes
    checking for ucontext... yes
    checking for g++... g++
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking for valgrind... no
    checking how to run the C++ preprocessor... g++ -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking for struct cmsghdr... yes
    checking for hstrerror... yes
    checking for socketpair... yes
    checking for if_nametoindex... yes
    checking for if_indextoname... yes
    checking netdb.h usability... yes
    checking netdb.h presence... yes
    checking for netdb.h... yes
    checking netinet/tcp.h usability... yes
    checking netinet/tcp.h presence... yes
    checking for netinet/tcp.h... yes
    checking sys/un.h usability... yes
    checking sys/un.h presence... yes
    checking for sys/un.h... yes
    checking sys/sockio.h usability... no
    checking sys/sockio.h presence... no
    checking for sys/sockio.h... no
    checking for field ss_family in struct sockaddr_storage... yes
    checking if getaddrinfo supports AI_V4MAPPED... yes
    checking if getaddrinfo supports AI_ALL... yes
    checking if getaddrinfo supports AI_IDN... yes
    checking if gethostbyname2_r is supported... yes
    checking for valgrind... no
    checking for clock_gettime in -lrt... yes
    checking openssl fallback dir... checking for SSL_connect in -lssl... yes
    checking for pg_config... not found
    configure: error: Cannot find libpq-fe.h. Please specify correct PostgreSQL installation path
    ERROR: `/tmp/pear/temp/openswoole/configure --with-php-config=/usr/bin/php-config --enable-sockets=y --enable-openssl=y --enable-http2=y --enable-mysqlnd=y --enable-swoole-json=y --enable-swoole-curl=y --with-postgres=n' failed

**Comment by benwills** [comment]
Note that I have just installed libpq-dev via apt, and the installation of openswoole-4.8.1 via pecl was successful.

Though I'd imagine if postgres support is optional and selected by the user, you may not intend for libpq-dev to be a dependency.

**Comment by doubaokun** [comment]
`--with-postgres=n` and `--with-postgres` should be removed if you don't like to support postgres

**Comment by benwills** [comment]
Installing from pecl, I'm prompted if I would like to add Postgres support. This isn't a configure option passed to the compilation process.
    
    enable sockets supports? [no] : y
    enable openssl support? [no] : y
    enable http2 support? [no] : y
    enable mysqlnd support? [no] : y
    enable json support? [no] : y
    enable curl support? [no] : y
    enable postgres support? [no] : n

**Comment by benwills** [comment]
Considering that reponding with 'y' is accepted as yes, I believe the installer should be changed to accept 'n' as no.

**Comment by doubaokun** [comment]
Will look into improving this, thanks @benwills .

**Comment by benwills** [comment]
Thanks. I definitely appreciate all your work on OpenSwoole. With a background in C, I love having such a close interface to the event loop, networking, etc.

**Comment by doubaokun** [comment]
It will be available in the next version.
